[package]
name = "main-base"
version = "0.1.0"
authors = ["developer <developer@wingchain.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.11"
app_dirs = "1.2.1"
toml = "0.5.6"
serde =  { version = "1.0.104", features=["derive"] }

primitives = { path = "../../../core/primitives" }
