[package]
name = "main-node"
version = "0.1.0"
authors = ["developer <developer@wingchain.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.11"

base = { package = "main-base", path = "../base" }
service = { package = "node-service", path = "../../../core/node/service" }
primitives = { path = "../../../core/primitives" }

[dev-dependencies]
assert_cmd = "0.12.0"
tempfile = "3.1.0"

[features]
build-dep-test = []
