[package]
name = "wingchain"
version = "0.1.0"
authors = ["developer <developer@wingchain.cn>"]
edition = "2018"
description = "An open source, easy to start and easy to scale block chain"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.11"
log = "0.4.0"
env_logger = "0.7.1"

primitives = { path ="../../core/primitives" }
init = { package = "main-init", path = "init" }
node = { package = "main-node", path = "node" }
base = { package = "main-base", path = "base" }
